-- Share links: generated by session owner, used to invite others
CREATE TABLE share_links (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  UUID NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
  created_by  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code        TEXT UNIQUE NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_share_links_code ON share_links (code) WHERE is_active = true;
CREATE INDEX idx_share_links_session ON share_links (session_id);

-- Session shares: tracks which users have accepted a share
CREATE TABLE session_shares (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  UUID NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  shared_by   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (session_id, user_id)
);

CREATE INDEX idx_session_shares_user ON session_shares (user_id);
CREATE INDEX idx_session_shares_session ON session_shares (session_id);

-- Unique constraint on understanding_state for per-user-per-concept upserts
-- (needed for bootstrapping shared user understanding state)
CREATE UNIQUE INDEX idx_understanding_user_session_concept
  ON understanding_state (session_id, concept_id, user_id);

-- RLS for new tables
ALTER TABLE share_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "share_links_owner_all" ON share_links
  FOR ALL USING (created_by = auth.uid())
  WITH CHECK (created_by = auth.uid());

CREATE POLICY "session_shares_user_read" ON session_shares
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "session_shares_insert" ON session_shares
  FOR INSERT WITH CHECK (user_id = auth.uid());
